
CREATE PROCEDURE [dbo].[sp_DeleteOrder]
	@OrdID INT,
	@LoginName NVARCHAR(MAX)
AS
BEGIN
declare @CheckInvCount int =0
  select  @CheckInvCount=ISNULL(count(*),0) from tblInvoice where OrderId=@OrdID

  print @CheckInvCount

  if(@CheckInvCount=0)
  begin
INSERT INTO dbo.tblOrderDel
        (  [OrderId]
      ,[OrderCode]
      ,[ComUnitId]
      ,[ComUnitCode]
      ,[ComUnitName]
      ,[MIOCode]
      ,[MIOName]
      ,[ManufacId]
      ,[CustomerCode]
      ,[CustomerName]
      ,[GrossValue]
      ,[SubmissionDate]
      ,[IsInvoice]
      ,[IsManual]
      ,[TerritoryCode]
      ,[CampaignName]
      ,[OrderSenderType]
      ,[OrderSenderCode]
      ,[OrderSenderName]
      ,[FixedCustomer]
      ,[CustomerType]
      ,[IsSpDis]
      ,[CustomerMasterId]
      ,[DeliveryPersonId]
      ,[IsSpecialApproval]
      ,[EntryBy]
      ,[EntryDate]
      ,[UpdateBy]
      ,[UpdateDate]
      ,[ApprovedBy]
      ,[ApprovedDate]
      ,[ActionStatus]
      ,[IsDirect]
      ,[IsFromApp]
      ,[Remarks]
      ,[OrderType]
      ,[DistributionRouteId]
      ,[RsmEmpId]
      ,[AsmEmpId]
      ,[TPDiscount]
      ,[ServerDateTime]
      ,[GroupId]
      ,[RegionId]
      ,[AreaId]
      ,[TerritoryId]
      ,[SubTerritoryId]
      ,[MarketId]
      ,[RSMId]
      ,[ASMId]
      ,[MIOId]
      ,[NSMId]
      ,[TotalVat]
      ,[TotalDiscount]
      ,[TotalNetPayable]
      ,[CustTypeId]
      ,[ProgramTypeId]
      ,[DeliveryDate]
      ,[IsSubDepo]
      ,[DelBy]
      ,[DelDate]
   

        )
SELECT   [OrderId]
      ,[OrderCode]
      ,[ComUnitId]
      ,[ComUnitCode]
      ,[ComUnitName]
      ,[MIOCode]
      ,[MIOName]
      ,[ManufacId]
      ,[CustomerCode]
      ,[CustomerName]
      ,[GrossValue]
      ,[SubmissionDate]
      ,[IsInvoice]
      ,[IsManual]
      ,[TerritoryCode]
      ,[CampaignName]
      ,[OrderSenderType]
      ,[OrderSenderCode]
      ,[OrderSenderName]
      ,[FixedCustomer]
      ,[CustomerType]
      ,[IsSpDis]
      ,[CustomerMasterId]
      ,[DeliveryPersonId]
      ,[IsSpecialApproval]
      ,[EntryBy]
      ,[EntryDate]
      ,[UpdateBy]
      ,[UpdateDate]
      ,[ApprovedBy]
      ,[ApprovedDate]
      ,[ActionStatus]
      ,[IsDirect]
      ,[IsFromApp]
      ,[Remarks]
      ,[OrderType]
      ,[DistributionRouteId]
      ,[RsmEmpId]
      ,[AsmEmpId]
      ,[TPDiscount]
      ,[ServerDateTime]
      ,[GroupId]
      ,[RegionId]
      ,[AreaId]
      ,[TerritoryId]
      ,[SubTerritoryId]
      ,[MarketId]
      ,[RSMId]
      ,[ASMId]
      ,[MIOId]
      ,[NSMId]
      ,[TotalVat]
      ,[TotalDiscount]
      ,[TotalNetPayable]
      ,[CustTypeId]
      ,[ProgramTypeId]
      ,[DeliveryDate]
      ,[IsSubDepo]
      ,@LoginName
      ,GETDATE()
  FROM [dbo].[tblOrder]
 WHERE OrderId=@OrdID


INSERT INTO dbo.tblOrderDetailDel
        ( [OrderDetailId]
      ,[ProductId]
      ,[ProductCode]
      ,[ProductName]
      ,[Quantity]
      ,[TradePrice]
      ,[TotalTradePrice]
      ,[OrderId]
      ,[OrderListDetailId]
      ,[Status]
      ,[ISGiftProduct]
      ,[CampaignType]
      ,[DiscountPercent]
      ,[DiscountAmount]
      ,[UnitVatAmount]
      ,[TotalVatAmount]
      ,[NetAmount]
      ,[CampaignName]
      ,[OrderSenderType]
      ,[OrderSenderCode]
      ,[OrderSenderName]
      ,[IsCampaignProduct]
      ,[IsSpDis]
        )
SELECT	 [OrderDetailId]
      ,[ProductId]
      ,[ProductCode]
      ,[ProductName]
      ,[Quantity]
      ,[TradePrice]
      ,[TotalTradePrice]
      ,[OrderId]
      ,[OrderListDetailId]
      ,[Status]
      ,[ISGiftProduct]
      ,[CampaignType]
      ,[DiscountPercent]
      ,[DiscountAmount]
      ,[UnitVatAmount]
      ,[TotalVatAmount]
      ,[NetAmount]
      ,[CampaignName]
      ,[OrderSenderType]
      ,[OrderSenderCode]
      ,[OrderSenderName]
      ,[IsCampaignProduct]
      ,[IsSpDis] FROM dbo.tblOrderDetail WHERE OrderId=@OrdID
	   
DELETE  FROM dbo.tblOrder WHERE OrderId=@OrdID
DELETE  FROM dbo.tblOrderDetail WHERE OrderId=@OrdID

END
END