
CREATE PROCEDURE [dbo].[sp_Pro_DZSMwiseReportParam] 

   
AS
BEGIN


INSERT INTO [dbo].[tblDZSMProcessDate]
           ([DZSMProcessDate])
     VALUES
           (GETDATE()) 
update    tbl_PrescriptionMaster set DoctorProgramypeId=9 where DoctorProgramypeId is null

update    tbl_DCRInfo set DoctorProgramypeId=9 where DoctorProgramypeId is null

delete from SalesDisDB_SMC_TrSalesRepor..tblEmpCountOrd  where  CONVERT(date,EntryDate)=CONVERT(date,getdate()) 
INSERT INTO SalesDisDB_SMC_TrSalesRepor..tblEmpCountOrd
           ( [EntryDate]
           
           ,[ORD]
           ,[EntryBy])
 select CONVERT(date,getdate()),  count(*), EntryBy from tblOrder where CONVERT(date,EntryDate)=CONVERT(date,getdate()) group by EntryBy


 
delete from SalesDisDB_SMC_TrSalesRepor..tblEmpCountRX  where  CONVERT(date,EntryDate)=CONVERT(date,getdate()) 
INSERT INTO SalesDisDB_SMC_TrSalesRepor..tblEmpCountRX
           ( [EntryDate]
           
           ,[RX]
           ,[EntryBy])
 select CONVERT(date,getdate()),  count(*), EntryBy from tbl_PrescriptionMaster where CONVERT(date,EntryDate)=CONVERT(date,getdate()) group by EntryBy


 
delete from SalesDisDB_SMC_TrSalesRepor..tblEmpCountDCR  where  CONVERT(date,EntryDate)=CONVERT(date,getdate()) 
INSERT INTO SalesDisDB_SMC_TrSalesRepor..tblEmpCountDCR
           ( [EntryDate]
           
           ,[DCR]
           ,[EntryBy])
 select CONVERT(date,getdate()),  count(*), EntryBy from tbl_DCRInfo where CONVERT(date,EntryDate)=CONVERT(date,getdate()) group by EntryBy


 truncate table SalesDisDB_SMC_TrSalesRepor..[tblTerritory]

INSERT INTO SalesDisDB_SMC_TrSalesRepor..[tblTerritory]
           ([AreaId]
           ,[TerritoryName]
           ,[TerritoryCode]
           ,[TerShortName]
           ,[Description]
           ,[Remarks]
           ,[IsActive]
           ,[EntryBy]
           ,[EntryDate]
           ,[UpdateBy]
           ,[UpdateDate]
           ,[AcOrInAcDate]
           ,[ActiveInactiveBy]
           ,[CodeStr]
           ,[TerritoryId])
    SELECT [AreaId]
      ,[TerritoryName]
      ,[TerritoryCode]
      ,[TerShortName]
      ,[Description]
      ,[Remarks]
      ,[IsActive]
      ,[EntryBy]
      ,[EntryDate]
      ,[UpdateBy]
      ,[UpdateDate]
      ,[AcOrInAcDate]
      ,[ActiveInactiveBy]
      ,[CodeStr]
      ,[TerritoryId]
  FROM SalesDisDB_SMC_NEWDB..[tblTerritory]






  truncate table SalesDisDB_SMC_TrSalesRepor..[tblOrder]

INSERT INTO SalesDisDB_SMC_TrSalesRepor..[tblOrder]
           ([OrderId]
      ,[OrderCode]
      ,[ComUnitId]
      ,[ComUnitCode]
      ,[ComUnitName]
      ,[MIOCode]
      ,[MIOName]
      ,[ManufacId]
      ,[CustomerCode]
      ,[CustomerName]
      ,[GrossValue]
      ,[SubmissionDate]
      ,[IsInvoice]
      ,[IsManual]
      ,[TerritoryCode]
      ,[CampaignName]
      ,[OrderSenderType]
      ,[OrderSenderCode]
      ,[OrderSenderName]
      ,[FixedCustomer]
      ,[CustomerType]
      ,[IsSpDis]
      ,[CustomerMasterId]
      ,[DeliveryPersonId]
      ,[IsSpecialApproval]
      ,[EntryBy]
      ,[EntryDate]
      ,[UpdateBy]
      ,[UpdateDate]
      ,[ApprovedBy]
      ,[ApprovedDate]
      ,[ActionStatus]
      ,[IsDirect]
      ,[IsFromApp]
      ,[Remarks]
      ,[OrderType]
      ,[DistributionRouteId]
      ,[RsmEmpId]
      ,[AsmEmpId]
      ,[TPDiscount]
      ,[ServerDateTime]
      ,[GroupId]
      ,[RegionId]
      ,[AreaId]
      ,[TerritoryId]
      ,[SubTerritoryId]
      ,[MarketId]
      ,[RSMId]
      ,[ASMId]
      ,[MIOId]
      ,[NSMId]
      ,[TotalVat]
      ,[TotalDiscount]
      ,[TotalNetPayable]
      ,[CustTypeId]
      ,[ProgramTypeId]
      ,[DeliveryDate]
      ,[IsSubDepo]
      ,[GroupName_Ord]
      ,[RegionName_Ord]
      ,[AreaName_Ord]
      ,[TerritoryName_Ord]
      ,[SubTerritoryName_Ord]
      ,[MarketName_Ord]
      ,[GroupCode_Ord]
      ,[RegionCode_Ord]
      ,[AreaCode_Ord]
      ,[TerritoryCode_Ord]
      ,[SubTerritoryCode_Ord]
      ,[MarketCode_Ord]
      ,[DistributionRoute_Ord]
      ,[SmcTypeId_Ord]
      ,[SMCType_Ord])
    SELECT [OrderId]
      ,[OrderCode]
      ,[ComUnitId]
      ,[ComUnitCode]
      ,[ComUnitName]
      ,[MIOCode]
      ,[MIOName]
      ,[ManufacId]
      ,[CustomerCode]
      ,[CustomerName]
      ,[GrossValue]
      ,[SubmissionDate]
      ,[IsInvoice]
      ,[IsManual]
      ,[TerritoryCode]
      ,[CampaignName]
      ,[OrderSenderType]
      ,[OrderSenderCode]
      ,[OrderSenderName]
      ,[FixedCustomer]
      ,[CustomerType]
      ,[IsSpDis]
      ,[CustomerMasterId]
      ,[DeliveryPersonId]
      ,[IsSpecialApproval]
      ,[EntryBy]
      ,[EntryDate]
      ,[UpdateBy]
      ,[UpdateDate]
      ,[ApprovedBy]
      ,[ApprovedDate]
      ,[ActionStatus]
      ,[IsDirect]
      ,[IsFromApp]
      ,[Remarks]
      ,[OrderType]
      ,[DistributionRouteId]
      ,[RsmEmpId]
      ,[AsmEmpId]
      ,[TPDiscount]
      ,[ServerDateTime]
      ,[GroupId]
      ,[RegionId]
      ,[AreaId]
      ,[TerritoryId]
      ,[SubTerritoryId]
      ,[MarketId]
      ,[RSMId]
      ,[ASMId]
      ,[MIOId]
      ,[NSMId]
      ,[TotalVat]
      ,[TotalDiscount]
      ,[TotalNetPayable]
      ,[CustTypeId]
      ,[ProgramTypeId]
      ,[DeliveryDate]
      ,[IsSubDepo]
      ,[GroupName_Ord]
      ,[RegionName_Ord]
      ,[AreaName_Ord]
      ,[TerritoryName_Ord]
      ,[SubTerritoryName_Ord]
      ,[MarketName_Ord]
      ,[GroupCode_Ord]
      ,[RegionCode_Ord]
      ,[AreaCode_Ord]
      ,[TerritoryCode_Ord]
      ,[SubTerritoryCode_Ord]
      ,[MarketCode_Ord]
      ,[DistributionRoute_Ord]
      ,[SmcTypeId_Ord]
      ,[SMCType_Ord]
  FROM SalesDisDB_SMC_NEWDB..[tblOrder]
 

 

  truncate table SalesDisDB_SMC_TrSalesRepor..[tblOrderDetail]

INSERT INTO SalesDisDB_SMC_TrSalesRepor..[tblOrderDetail]
           ([OrderDetailId]
      ,[ProductId]
      ,[ProductCode]
      ,[ProductName]
      ,[Quantity]
      ,[TradePrice]
      ,[TotalTradePrice]
      ,[OrderId]
      ,[OrderListDetailId]
      ,[Status]
      ,[ISGiftProduct]
      ,[CampaignType]
      ,[DiscountPercent]
      ,[DiscountAmount]
      ,[UnitVatAmount]
      ,[TotalVatAmount]
      ,[NetAmount]
      ,[CampaignName]
      ,[OrderSenderType]
      ,[OrderSenderCode]
      ,[OrderSenderName]
      ,[IsCampaignProduct]
      ,[IsSpDis])
    SELECT [OrderDetailId]
      ,[ProductId]
      ,[ProductCode]
      ,[ProductName]
      ,[Quantity]
      ,[TradePrice]
      ,[TotalTradePrice]
      ,[OrderId]
      ,[OrderListDetailId]
      ,[Status]
      ,[ISGiftProduct]
      ,[CampaignType]
      ,[DiscountPercent]
      ,[DiscountAmount]
      ,[UnitVatAmount]
      ,[TotalVatAmount]
      ,[NetAmount]
      ,[CampaignName]
      ,[OrderSenderType]
      ,[OrderSenderCode]
      ,[OrderSenderName]
      ,[IsCampaignProduct]
      ,[IsSpDis]
  FROM SalesDisDB_SMC_NEWDB..[tblOrderDetail]
 

  truncate table SalesDisDB_SMC_TrSalesRepor..[tblArea]

INSERT INTO SalesDisDB_SMC_TrSalesRepor..[tblArea]
           ([AreaCode]
      ,[AreaName]
      ,[RegionId]
      ,[AreaId]
      ,[New]
      ,[DistrictId]
      ,[MiaId]
      ,[IsActive]
      ,[AcOrInAcDate]
      ,[EntryBy]
      ,[EntryDate]
      ,[UpdateBy]
      ,[UpdateDate]
      ,[Remarks]
      ,[ActiveInactiveBy]
      ,[CodeStr])
    SELECT [AreaCode]
      ,[AreaName]
      ,[RegionId]
      ,[AreaId]
      ,[New]
      ,[DistrictId]
      ,[MiaId]
      ,[IsActive]
      ,[AcOrInAcDate]
      ,[EntryBy]
      ,[EntryDate]
      ,[UpdateBy]
      ,[UpdateDate]
      ,[Remarks]
      ,[ActiveInactiveBy]
      ,[CodeStr]
  FROM SalesDisDB_SMC_NEWDB..[tblArea]



    truncate table SalesDisDB_SMC_TrSalesRepor..tblInvoice

INSERT INTO SalesDisDB_SMC_TrSalesRepor..tblInvoice
           ([InvoiceId]
      ,[InvoiceNo]
      ,[InvoiceDate]
      ,[OrderId]
      ,[OrderNo]
      ,[OrderDate]
      ,[CustomerMasterId]
      ,[ComUnitId]
      ,[MiaId]
      ,[PaymentTypeId]
      ,[TpTotal]
      ,[TpDiscount]
      ,[TpVat]
      ,[TpGrandTotal]
      ,[UserId]
      ,[DeliveryTpTotal]
      ,[DeliveryTpDiscount]
      ,[DeliveryTpVat]
      ,[DeliveryTpGrandTotal]
      ,[DeliveryInvoiceStatus]
      ,[DelivaryInvoiceNo]
      ,[CreateBy]
      ,[CreateDate]
      ,[UpdateBy]
      ,[UpdateDate]
      ,[TotalSpecialAmount]
      ,[DelivarySpecialAmount]
      ,[PaymentAmount]
      ,[PaymentStatus]
      ,[ProductOffer]
      ,[OldTradePolicy]
      ,[Remarks]
      ,[FixedCustomer]
      ,[MIACode]
      ,[MIAName]
      ,[MarketCode]
      ,[MarketName]
      ,[AreaCode]
      ,[DisCode]
      ,[FEName]
      ,[RegionCode]
      ,[DZSMName]
      ,[DeliveryPersonName]
      ,[DeliveryPersonPhNo]
      ,[Types]
      ,[GreenStarBlueStarID]
      ,[AdjustAmount]
      ,[IsAdjustInvoice]
      ,[ReceivableAmount]
      ,[IsSalesTransfer]
      ,[TransferInvoiceDate]
      ,[UpdateDatetime]
      ,[CampaignName]
      ,[OrderSenderType]
      ,[OrderSenderCode]
      ,[OrderSenderName]
      ,[CustomerType]
      ,[AdjustInvoiceNo_ReturnInvoiceNo]
      ,[DeliveryManId]
      ,[AIT]
      ,[DiscountOnPayment]
      ,[IsPosting]
      ,[MIOId]
      ,[IsAuto], [PaymentTpTotal]
      ,[PaymentTpDiscount]
      ,[PaymentTpVat]
      ,[PaymentTpGrandTotal]
      ,[PaymentInvoiceStatus]
      ,[PaymentInvoiceNo]
      ,[PaymentBy]
      ,[PaymentDate]
      ,[FinalPaymentBy]
      ,[FinalPaymentDate]
      ,[RejectionSts]
      ,[FinalPaymentNo])
    SELECT [InvoiceId]
      ,[InvoiceNo]
      ,[InvoiceDate]
      ,[OrderId]
      ,[OrderNo]
      ,[OrderDate]
      ,[CustomerMasterId]
      ,[ComUnitId]
      ,[MiaId]
      ,[PaymentTypeId]
      ,[TpTotal]
      ,[TpDiscount]
      ,[TpVat]
      ,[TpGrandTotal]
      ,[UserId]
      ,[DeliveryTpTotal]
      ,[DeliveryTpDiscount]
      ,[DeliveryTpVat]
      ,[DeliveryTpGrandTotal]
      ,[DeliveryInvoiceStatus]
      ,[DelivaryInvoiceNo]
      ,[CreateBy]
      ,[CreateDate]
      ,[UpdateBy]
      ,[UpdateDate]
      ,[TotalSpecialAmount]
      ,[DelivarySpecialAmount]
      ,[PaymentAmount]
      ,[PaymentStatus]
      ,[ProductOffer]
      ,[OldTradePolicy]
      ,[Remarks]
      ,[FixedCustomer]
      ,[MIACode]
      ,[MIAName]
      ,[MarketCode]
      ,[MarketName]
      ,[AreaCode]
      ,[DisCode]
      ,[FEName]
      ,[RegionCode]
      ,[DZSMName]
      ,[DeliveryPersonName]
      ,[DeliveryPersonPhNo]
      ,[Types]
      ,[GreenStarBlueStarID]
      ,[AdjustAmount]
      ,[IsAdjustInvoice]
      ,[ReceivableAmount]
      ,[IsSalesTransfer]
      ,[TransferInvoiceDate]
      ,[UpdateDatetime]
      ,[CampaignName]
      ,[OrderSenderType]
      ,[OrderSenderCode]
      ,[OrderSenderName]
      ,[CustomerType]
      ,[AdjustInvoiceNo_ReturnInvoiceNo]
      ,[DeliveryManId]
      ,[AIT]
      ,[DiscountOnPayment]
      ,[IsPosting]
      ,[MIOId]
      ,[IsAuto],[PaymentTpTotal]
      ,[PaymentTpDiscount]
      ,[PaymentTpVat]
      ,[PaymentTpGrandTotal]
      ,[PaymentInvoiceStatus]
      ,[PaymentInvoiceNo]
      ,[PaymentBy]
      ,[PaymentDate]
      ,[FinalPaymentBy]
      ,[FinalPaymentDate]
      ,[RejectionSts]
      ,[FinalPaymentNo]
  FROM SalesDisDB_SMC_NEWDB..tblInvoice





  


    truncate table SalesDisDB_SMC_TrSalesRepor..tblInvoiceDetail

INSERT INTO SalesDisDB_SMC_TrSalesRepor..tblInvoiceDetail
           ( [InvoiceDetailId]
      ,[ProductCode]
      ,[ProductName]
      ,[PackSize]
      ,[BatchNo]
      ,[ReceiveDate]
      ,[ExpDate]
      ,[CostPrice]
      ,[UnitPrice]
      ,[UnitVatAmount]
      ,[Quantity]
      ,[BonusQuantity]
      ,[TotalQuantity]
      ,[TotalPrice]
      ,[TotalPriceVatAmount]
      ,[DiscountPercentage]
      ,[DiscountAmount]
      ,[NetAmount]
      ,[InvoiceId]
      ,[DCStoreId]
      ,[DeliveryQuantity]
      ,[DeliveryBonusQuantity]
      ,[DeliveryTotalQuantity]
      ,[DeliveryTotalPrice]
      ,[DeliveryTotalPriceVatAmount]
      ,[DeliveryDiscountPercentage]
      ,[DeliveryDiscountAmount]
      ,[DeliveryNetAmount]
      ,[DeliveryStatus]
      ,[OrderDetailsId]
      ,[SpecialAmount]
      ,[DelivarySpecialAmount]
      ,[ReturnReason]
      ,[Campaign]
      ,[ISGiftProduct]
      ,[CampaignType]
      ,[IsCampaignProduct]
      ,[AdjustmentAmount],[PaymentQuantity]
      ,[PaymentBonusQuantity]
      ,[PaymentTotalQuantity]
      ,[PaymentTotalPrice]
      ,[PaymentTotalPriceVatAmount]
      ,[PaymentDiscountPercentage]
      ,[PaymentDiscountAmount]
      ,[PaymentNetAmount]
      ,[PaymentReturnReason]
      ,[PaymentStatus])
    SELECT  [InvoiceDetailId]
      ,[ProductCode]
      ,[ProductName]
      ,[PackSize]
      ,[BatchNo]
      ,[ReceiveDate]
      ,[ExpDate]
      ,[CostPrice]
      ,[UnitPrice]
      ,[UnitVatAmount]
      ,[Quantity]
      ,[BonusQuantity]
      ,[TotalQuantity]
      ,[TotalPrice]
      ,[TotalPriceVatAmount]
      ,[DiscountPercentage]
      ,[DiscountAmount]
      ,[NetAmount]
      ,[InvoiceId]
      ,[DCStoreId]
      ,[DeliveryQuantity]
      ,[DeliveryBonusQuantity]
      ,[DeliveryTotalQuantity]
      ,[DeliveryTotalPrice]
      ,[DeliveryTotalPriceVatAmount]
      ,[DeliveryDiscountPercentage]
      ,[DeliveryDiscountAmount]
      ,[DeliveryNetAmount]
      ,[DeliveryStatus]
      ,[OrderDetailsId]
      ,[SpecialAmount]
      ,[DelivarySpecialAmount]
      ,[ReturnReason]
      ,[Campaign]
      ,[ISGiftProduct]
      ,[CampaignType]
      ,[IsCampaignProduct]
      ,[AdjustmentAmount],[PaymentQuantity]
      ,[PaymentBonusQuantity]
      ,[PaymentTotalQuantity]
      ,[PaymentTotalPrice]
      ,[PaymentTotalPriceVatAmount]
      ,[PaymentDiscountPercentage]
      ,[PaymentDiscountAmount]
      ,[PaymentNetAmount]
      ,[PaymentReturnReason]
      ,[PaymentStatus]
  FROM SalesDisDB_SMC_NEWDB..tblInvoiceDetail



  

   
 
  

  


    truncate table SalesDisDB_SMC_TrSalesRepor..tbl_BonusCampaignNewDetail

INSERT INTO SalesDisDB_SMC_TrSalesRepor..tbl_BonusCampaignNewDetail
           ( [CampaignDetailId]
      ,[CampaignMasterId]
      ,[DiscountPercentage]
      ,[DiscountAmount]
      ,[ProductId]
      ,[Quantity]
      ,[BonusProductId]
      ,[BonusQuantity]
      ,[BonusTypeId]
      ,[CampaignName]
      ,[MinAmount]
      ,[MaxAmount]
      ,[BonusProductCode]
      ,[ProductCode]
      ,[QuantityDteail])
    SELECT  [CampaignDetailId]
      ,[CampaignMasterId]
      ,[DiscountPercentage]
      ,[DiscountAmount]
      ,[ProductId]
      ,[Quantity]
      ,[BonusProductId]
      ,[BonusQuantity]
      ,[BonusTypeId]
      ,[CampaignName]
      ,[MinAmount]
      ,[MaxAmount]
      ,[BonusProductCode]
      ,[ProductCode]
      ,[QuantityDteail]
  FROM SalesDisDB_SMC_NEWDB..tbl_BonusCampaignNewDetail

  


    truncate table SalesDisDB_SMC_TrSalesRepor..tbl_BonusCampaignNewMaster

INSERT INTO SalesDisDB_SMC_TrSalesRepor..tbl_BonusCampaignNewMaster
           ( [CampgainMasterId]
      ,[CampaignCode]
      ,[ProductLineID]
      ,[EntryBy]
      ,[EntryDate]
      ,[CompanyId]
      ,[CampaignName]
      ,[CampaignDesc]
      ,[FromDate]
      ,[Todate]
      ,[CampainTypeId]
      ,[IsActive]
      ,[CustomerTypeId]
      ,[Amount]
      ,[MaxAmount]
      ,[ProductQty]
      ,[IsTradePolicy]
      ,[BonusProductId]
      ,[UpdateBy]
      ,[UpdateDate])
    SELECT  [CampgainMasterId]
      ,[CampaignCode]
      ,[ProductLineID]
      ,[EntryBy]
      ,[EntryDate]
      ,[CompanyId]
      ,[CampaignName]
      ,[CampaignDesc]
      ,[FromDate]
      ,[Todate]
      ,[CampainTypeId]
      ,[IsActive]
      ,[CustomerTypeId]
      ,[Amount]
      ,[MaxAmount]
      ,[ProductQty]
      ,[IsTradePolicy]
      ,[BonusProductId]
      ,[UpdateBy]
      ,[UpdateDate]
  FROM SalesDisDB_SMC_NEWDB..tbl_BonusCampaignNewMaster
 

END

