CREATE   FUNCTION F_FIRST_N_WEEKDATES (@A_DATE DATETIME2, @N TINYINT)
RETURNS @T TABLE (D DATE)
AS
BEGIN
DECLARE @D DATE = DATEFROMPARTS(YEAR(@A_DATE), MONTH(@A_DATE), 1);
WHILE @N > 0
BEGIN
   INSERT INTO @T VALUES (@D);
   SELECT @D = DATEADD(day, 1, @D), @N-=1;
END
RETURN;
END;
